from enum import StrEnum

class Events(StrEnum):

    COMPONENT_DELETED = 'COMPONENT_DELETED'
    COMPONENT_CREATED = 'COMPONENT_CREATED'
    COMPONENT_UPDATED = 'COMPONENT_UPDATED'
    ON_START_UP = 'ON_START_UP'