from enum import StrEnum

class EventType(StrEnum):
    ADDED_REPO = 'ADDED_REPO'
    UPDATED_REPO = 'UPDATED_REPO'
    DELETED_REPO = 'DELETED_REPO'
    ON_STARTUP = 'ON_STARTUP'
    UPDATED_COMPONENT = 'UPDATED_COMPONENT'
    DELETED_COMPONENT = 'DELETED_COMPONENT'
    BUILD_DOCS = 'BUILD_DOCS'
    MOVE_DOCS = 'MOVE_DOCS'
    DELETED_DOCUMENTATION = 'DELETED_DOCUMENTATION'

